# Generated by Django 4.1.7 on 2023-05-27 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField(max_length=40)),
                ('RoomHostName', models.CharField(max_length=20)),
                ('RoomID', models.CharField(max_length=8)),
                ('UsersAmount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(10)])),
                ('IsGame', models.BooleanField(default=0)),
            ],
        ),
    ]
