# Generated by Django 4.1.7 on 2023-05-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbypage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='RoomHostName',
            new_name='roomHostName',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='RoomName',
            new_name='roomname',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='RoomID',
        ),
        migrations.AddField(
            model_name='rooms',
            name='roomID',
            field=models.CharField(default='STOCKID', max_length=8),
        ),
    ]
