# Generated by Django 4.1.7 on 2023-05-31 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbypage', '0002_rename_roomhostname_rooms_roomhostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='players',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='UsersAmount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
