# Generated by Django 4.1.7 on 2023-05-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobbypage', '0004_rename_roomhostname_rooms_roomhostid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='players',
        ),
    ]
