# Generated by Django 4.1.7 on 2023-06-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobbypage', '0007_roommember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomMember',
        ),
    ]
