# Generated by Django 4.1.7 on 2023-06-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbypage', '0009_rooms_votelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='votelist',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
