# Generated by Django 4.1.7 on 2023-05-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbypage', '0002_rename_roomhostname_rooms_roomhostname_and_more'),
        ('user_profile', '0003_alter_profile_nickname_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='related_lobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lobbypage.rooms'),
        ),
    ]
