# Generated by Django 4.1.7 on 2023-06-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_profile_slug'),
        ('user_profile', '0004_profile_related_lobby'),
    ]

    operations = [
    ]
