# Generated by Django 4.1.7 on 2023-06-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbypage', '0009_rooms_votelist'),
        ('user_profile', '0006_alter_profile_related_lobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='related_lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lobbypage.rooms', verbose_name='Связанное лобби'),
        ),
    ]
