# Generated by Django 4.1.7 on 2023-06-05 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbypage', '0008_delete_roommember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0006_alter_profile_related_lobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='related_lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lobbypage.rooms', verbose_name='Связанное лобби'),
        ),
        migrations.CreateModel(
            name='NoticeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('notice_type', models.CharField(choices=[('FR', 'Friendship'), ('IV', 'Invite'), ('IF', 'Info')], default='IF', max_length=2, verbose_name='Тип уведомления')),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile', verbose_name='Адресат')),
                ('invite_lobby', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lobbypage.rooms', verbose_name='Лобби диз приглашения')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
