# Generated by Django 4.1.7 on 2023-06-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_profile_related_lobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=40)),
                ('data', models.DateField()),
                ('win', models.IntegerField(default=-1)),
                ('playerlist', models.JSONField(default=dict, null=True)),
                ('players', models.ManyToManyField(to='user_profile.profile')),
            ],
        ),
    ]
