# Generated by Django 4.1.7 on 2023-06-06 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobbypage', '0008_delete_roommember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0008_notice_delete_noticemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='invite_lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lobbypage.rooms', verbose_name='Лобби диз приглашения'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
