# Generated by Django 4.1.7 on 2023-06-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_friends_alter_notice_invite_lobby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='user_profile.profile'),
        ),
    ]
