# Generated by Django 4.1.7 on 2023-06-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
