# Generated by Django 4.1.7 on 2023-06-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_friend_delete_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='text_message',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сообщение'),
        ),
    ]
