# Generated by Django 4.1.7 on 2023-06-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_gamehistory'),
        ('user_profile', '0014_alter_notice_text_message'),
    ]

    operations = [
    ]
