# Generated by Django 4.1.7 on 2023-06-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_merge_0008_gamehistory_0014_alter_notice_text_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': 'Друзья', 'verbose_name_plural': 'Друзья'},
        ),
    ]
